import type { Metadata } from "next";
// import localFont from "next/font/local";
import Footer from "@/ui/footer";
import "./globals.css";
import Container from "./components/Pages/Container";
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import { BackgroundBeamsWithCollision } from "@/components/ui/background-beams-with-collision";
import { FloatingDockDemo } from "@/ui/floating-dock";
import { Toaster } from "@/components/ui/toaster";
config.autoAddCss = false

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Alfiansah Erik Sugiarto",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white">
      <BackgroundBeamsWithCollision>
        <Container>
        {/* <NavLinks /> */}
        <main className="mb-10">{children}</main>
        <FloatingDockDemo />
        <Toaster />
        </Container>
        </BackgroundBeamsWithCollision>
      </body>
    </html>
  )
}
